### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by jpieres** [limiaspasdaniel/BenefitsCalculator#1]
In Readme the repository name in:

`$ git clone git@github.com:limiaspasdaniel/YearlyBenefitsCalculator.git`

is not updated with the name of the repo.

**Comment by 2snEM6** [comment]
Fixed [here](https://github.com/limiaspasdaniel/BenefitsCalculator/tree/065d8e0be5f8fe4fc2de5667004e06fcb277ca62)
